### PR TITLE
Making compatible with omniauth-oauth2 version 1.2.0

### PR DESCRIPTION
**Pull request by alexandrebini**
## What?

Making compatible with omniauth-oauth2 version 1.2.0
## Why?

We're using an old version, making incompatible with updated projects (including our https://github.com/teambox/redbooth-ruby)

gif

### CODE REVIEW

**Comment by masylum** [comment]
:+1:

**Comment by alexandrebini** [comment]
@masylum you are really fast xD

**Comment by jrom** [comment]
:+1: great work @alexandrebini

**Comment by alexandrebini** [comment]
@bpedro Could you please do the magic? =)

**Pull request merged**
